### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by KalobTaulien** [prijme/pet#3]
Hey Paul, 

This is fantastic work, and your videos are amazing! I'd love to share your videos on learnwagtail.com - reach out to me via https://learnwagtail.com/contact/ (to avoid sharing email addresses here) and let's have a conversation. I'd really love to get your videos in front of more eyes! 

Cheers,

Kalob

P.S. This isn't a real issue, it was just the only way I could reach out to you. Feel free to close this issue.

**Comment by prijme** [comment]
Thanks for reaching out, glad we've found each other! Closing the issue.
